### PR TITLE
Adds green & bigger whatsapp button and new placement

### PR DESCRIPTION
**Pull request by shakalee14**
For phase 2 of testing, adds a bigger button in between Email and Facebook share buttons. Reminder, this will be only shown to users with `cohort=1` in their petition url query string.

Connected to https://github.com/MoveOnOrg/giraffe/pull/258 (for updated button margins and a smaller font size to account for 3 buttons)

Screen shots:

Desktop with 3 buttons and WhatsApp green button:
Screen Shot 2019-03-18 at 1 43 23 PM

Desktop with 2 buttons (without WhatsApp green button):
Screen Shot 2019-03-18 at 1 48 16 PM

Mobile with 3 buttons and WhatsApp green button:
Screen Shot 2019-03-18 at 1 46 50 PM

Mobile with 2 buttons (without WhatsApp green button):
Screen Shot 2019-03-18 at 1 48 31 PM

### CODE REVIEW

**Comment by shakalee14** [comment]
@sreynen - thanks for the review. This PR will still need a UX review, but thanks for reviewing the code.

Note - I plan to refactor a lot of this code once testing is finished - especially all the duplicated code across share links and buttons.

**Comment by hi0ctane** [comment]
looks good! talked to Shaka and strongly recommending that if the whats app button uses its brand color, all other share buttons should use their brand colors as well.

**Comment by shakalee14** [comment]
tracking event being sent to segment looks like this -->
{"experiment":"whatsAppShare","variationname":"cohort1","user_sighash":"xxxx", user_signonid: xxxx}

user_sighash, usersignonid, experiment and variationnname will appear as columns in the `whatsapp` table

**Comment by shakalee14** [comment]
Closing this PR since we're not doing a green button for now

**Pull request closed without merging**
