### PR TITLE
Update document title as route changes

### LINKED ISSUE #315: Update page <title> as route changes
For static pages, title comes from API. For everything else, maybe just hard-code them?

### PR DESCRIPTION
**Pull request by jparkrr**
fixes #315 

See https://github.com/gaearon/react-document-title for an explanation of the component I use. I think it's a pretty small dependency, and it fits pretty well with our container elements that aren't deeply nested.

The legacy system doesn't actually have that many titles, so I based most of these on the header of the page.

### CODE REVIEW

**Comment by jparkrr** [comment]
I'll leave this up for a while so people can look over the titles if they want.

**Comment by jparkrr** [comment]
@schuyler1d right now I don't foresee too many problems, as long as we use `find()` in tests.

Here someone implemented a higher order component to do it: https://github.com/rrdelaney/react-page-title/blob/master/index.js, but it would still have to receive props from redux, so the end result would be similar, but with different syntax.

I think it's ok to go with the simplest solution until we see any problems, and then we can refactor. 

But if we really don't like wrappers, we can switch to [react-helmet](https://github.com/nfl/react-helmet), which doesn't actually require a wrapper and can be anywhere in the tree:
```jsx
<Parent>
    <Helmet>
        <title>My Title</title>
    </Helmet>

    <Child>
        <Helmet>
            <title>Nested Title</title>
        </Helmet>
    </Child>
</Parent>
```

**Comment by schuyler1d** [comment]
ok, i'm :+1:  then -- I don't have any opinions on DocumentTitle vs. helmet -- choose the one that you (and/or @sreynen ) thinks best.

**Comment by jparkrr** [comment]
@sreynen any thoughts?

**Comment by sreynen** [comment]
This looks good to me.

**Comment by jparkrr** [comment]
Thanks for the reviews!

**Pull request merged**
